-- Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2019.1 (lin64) Build 2552052 Fri May 24 14:47:09 MDT 2019
-- Date        : Wed Sep 23 16:59:06 2020
-- Host        : torreys.colorado.edu running 64-bit CentOS Linux release 7.7.1908 (Core)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvu9p-flgc2104-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    score_0_V_ap_vld : out STD_LOGIC;
    tree_scores_0_V_ap_vld : out STD_LOGIC;
    tree_scores_1_V_ap_vld : out STD_LOGIC;
    tree_scores_2_V_ap_vld : out STD_LOGIC;
    tree_scores_3_V_ap_vld : out STD_LOGIC;
    tree_scores_4_V_ap_vld : out STD_LOGIC;
    tree_scores_5_V_ap_vld : out STD_LOGIC;
    tree_scores_6_V_ap_vld : out STD_LOGIC;
    tree_scores_7_V_ap_vld : out STD_LOGIC;
    tree_scores_8_V_ap_vld : out STD_LOGIC;
    tree_scores_9_V_ap_vld : out STD_LOGIC;
    tree_scores_10_V_ap_vld : out STD_LOGIC;
    tree_scores_11_V_ap_vld : out STD_LOGIC;
    tree_scores_12_V_ap_vld : out STD_LOGIC;
    tree_scores_13_V_ap_vld : out STD_LOGIC;
    tree_scores_14_V_ap_vld : out STD_LOGIC;
    tree_scores_15_V_ap_vld : out STD_LOGIC;
    tree_scores_16_V_ap_vld : out STD_LOGIC;
    tree_scores_17_V_ap_vld : out STD_LOGIC;
    tree_scores_18_V_ap_vld : out STD_LOGIC;
    tree_scores_19_V_ap_vld : out STD_LOGIC;
    tree_scores_20_V_ap_vld : out STD_LOGIC;
    tree_scores_21_V_ap_vld : out STD_LOGIC;
    tree_scores_22_V_ap_vld : out STD_LOGIC;
    tree_scores_23_V_ap_vld : out STD_LOGIC;
    tree_scores_24_V_ap_vld : out STD_LOGIC;
    tree_scores_25_V_ap_vld : out STD_LOGIC;
    tree_scores_26_V_ap_vld : out STD_LOGIC;
    tree_scores_27_V_ap_vld : out STD_LOGIC;
    tree_scores_28_V_ap_vld : out STD_LOGIC;
    tree_scores_29_V_ap_vld : out STD_LOGIC;
    tree_scores_30_V_ap_vld : out STD_LOGIC;
    tree_scores_31_V_ap_vld : out STD_LOGIC;
    tree_scores_32_V_ap_vld : out STD_LOGIC;
    tree_scores_33_V_ap_vld : out STD_LOGIC;
    tree_scores_34_V_ap_vld : out STD_LOGIC;
    tree_scores_35_V_ap_vld : out STD_LOGIC;
    tree_scores_36_V_ap_vld : out STD_LOGIC;
    tree_scores_37_V_ap_vld : out STD_LOGIC;
    tree_scores_38_V_ap_vld : out STD_LOGIC;
    tree_scores_39_V_ap_vld : out STD_LOGIC;
    tree_scores_40_V_ap_vld : out STD_LOGIC;
    tree_scores_41_V_ap_vld : out STD_LOGIC;
    tree_scores_42_V_ap_vld : out STD_LOGIC;
    tree_scores_43_V_ap_vld : out STD_LOGIC;
    tree_scores_44_V_ap_vld : out STD_LOGIC;
    tree_scores_45_V_ap_vld : out STD_LOGIC;
    tree_scores_46_V_ap_vld : out STD_LOGIC;
    tree_scores_47_V_ap_vld : out STD_LOGIC;
    tree_scores_48_V_ap_vld : out STD_LOGIC;
    tree_scores_49_V_ap_vld : out STD_LOGIC;
    tree_scores_50_V_ap_vld : out STD_LOGIC;
    tree_scores_51_V_ap_vld : out STD_LOGIC;
    tree_scores_52_V_ap_vld : out STD_LOGIC;
    tree_scores_53_V_ap_vld : out STD_LOGIC;
    tree_scores_54_V_ap_vld : out STD_LOGIC;
    tree_scores_55_V_ap_vld : out STD_LOGIC;
    tree_scores_56_V_ap_vld : out STD_LOGIC;
    tree_scores_57_V_ap_vld : out STD_LOGIC;
    tree_scores_58_V_ap_vld : out STD_LOGIC;
    tree_scores_59_V_ap_vld : out STD_LOGIC;
    tree_scores_60_V_ap_vld : out STD_LOGIC;
    tree_scores_61_V_ap_vld : out STD_LOGIC;
    tree_scores_62_V_ap_vld : out STD_LOGIC;
    tree_scores_63_V_ap_vld : out STD_LOGIC;
    tree_scores_64_V_ap_vld : out STD_LOGIC;
    tree_scores_65_V_ap_vld : out STD_LOGIC;
    tree_scores_66_V_ap_vld : out STD_LOGIC;
    tree_scores_67_V_ap_vld : out STD_LOGIC;
    tree_scores_68_V_ap_vld : out STD_LOGIC;
    tree_scores_69_V_ap_vld : out STD_LOGIC;
    tree_scores_70_V_ap_vld : out STD_LOGIC;
    tree_scores_71_V_ap_vld : out STD_LOGIC;
    tree_scores_72_V_ap_vld : out STD_LOGIC;
    tree_scores_73_V_ap_vld : out STD_LOGIC;
    tree_scores_74_V_ap_vld : out STD_LOGIC;
    tree_scores_75_V_ap_vld : out STD_LOGIC;
    tree_scores_76_V_ap_vld : out STD_LOGIC;
    tree_scores_77_V_ap_vld : out STD_LOGIC;
    tree_scores_78_V_ap_vld : out STD_LOGIC;
    tree_scores_79_V_ap_vld : out STD_LOGIC;
    tree_scores_80_V_ap_vld : out STD_LOGIC;
    tree_scores_81_V_ap_vld : out STD_LOGIC;
    tree_scores_82_V_ap_vld : out STD_LOGIC;
    tree_scores_83_V_ap_vld : out STD_LOGIC;
    tree_scores_84_V_ap_vld : out STD_LOGIC;
    tree_scores_85_V_ap_vld : out STD_LOGIC;
    tree_scores_86_V_ap_vld : out STD_LOGIC;
    tree_scores_87_V_ap_vld : out STD_LOGIC;
    tree_scores_88_V_ap_vld : out STD_LOGIC;
    tree_scores_89_V_ap_vld : out STD_LOGIC;
    tree_scores_90_V_ap_vld : out STD_LOGIC;
    tree_scores_91_V_ap_vld : out STD_LOGIC;
    tree_scores_92_V_ap_vld : out STD_LOGIC;
    tree_scores_93_V_ap_vld : out STD_LOGIC;
    tree_scores_94_V_ap_vld : out STD_LOGIC;
    tree_scores_95_V_ap_vld : out STD_LOGIC;
    tree_scores_96_V_ap_vld : out STD_LOGIC;
    tree_scores_97_V_ap_vld : out STD_LOGIC;
    tree_scores_98_V_ap_vld : out STD_LOGIC;
    tree_scores_99_V_ap_vld : out STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst : in STD_LOGIC;
    ap_start : in STD_LOGIC;
    ap_done : out STD_LOGIC;
    ap_idle : out STD_LOGIC;
    ap_ready : out STD_LOGIC;
    x_0_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_1_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_2_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_3_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_4_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_5_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    x_6_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    score_0_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    score_1_V : in STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_0_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_1_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_2_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_3_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_4_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_5_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_6_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_7_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_8_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_9_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_10_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_11_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_12_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_13_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_14_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_15_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_16_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_17_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_18_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_19_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_20_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_21_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_22_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_23_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_24_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_25_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_26_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_27_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_28_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_29_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_30_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_31_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_32_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_33_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_34_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_35_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_36_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_37_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_38_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_39_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_40_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_41_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_42_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_43_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_44_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_45_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_46_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_47_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_48_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_49_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_50_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_51_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_52_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_53_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_54_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_55_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_56_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_57_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_58_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_59_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_60_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_61_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_62_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_63_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_64_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_65_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_66_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_67_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_68_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_69_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_70_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_71_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_72_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_73_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_74_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_75_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_76_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_77_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_78_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_79_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_80_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_81_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_82_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_83_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_84_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_85_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_86_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_87_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_88_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_89_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_90_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_91_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_92_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_93_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_94_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_95_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_96_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_97_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_98_V : out STD_LOGIC_VECTOR ( 10 downto 0 );
    tree_scores_99_V : out STD_LOGIC_VECTOR ( 10 downto 0 )
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "score_0_V_ap_vld,tree_scores_0_V_ap_vld,tree_scores_1_V_ap_vld,tree_scores_2_V_ap_vld,tree_scores_3_V_ap_vld,tree_scores_4_V_ap_vld,tree_scores_5_V_ap_vld,tree_scores_6_V_ap_vld,tree_scores_7_V_ap_vld,tree_scores_8_V_ap_vld,tree_scores_9_V_ap_vld,tree_scores_10_V_ap_vld,tree_scores_11_V_ap_vld,tree_scores_12_V_ap_vld,tree_scores_13_V_ap_vld,tree_scores_14_V_ap_vld,tree_scores_15_V_ap_vld,tree_scores_16_V_ap_vld,tree_scores_17_V_ap_vld,tree_scores_18_V_ap_vld,tree_scores_19_V_ap_vld,tree_scores_20_V_ap_vld,tree_scores_21_V_ap_vld,tree_scores_22_V_ap_vld,tree_scores_23_V_ap_vld,tree_scores_24_V_ap_vld,tree_scores_25_V_ap_vld,tree_scores_26_V_ap_vld,tree_scores_27_V_ap_vld,tree_scores_28_V_ap_vld,tree_scores_29_V_ap_vld,tree_scores_30_V_ap_vld,tree_scores_31_V_ap_vld,tree_scores_32_V_ap_vld,tree_scores_33_V_ap_vld,tree_scores_34_V_ap_vld,tree_scores_35_V_ap_vld,tree_scores_36_V_ap_vld,tree_scores_37_V_ap_vld,tree_scores_38_V_ap_vld,tree_scores_39_V_ap_vld,tree_scores_40_V_ap_vld,tree_scores_41_V_ap_vld,tree_scores_42_V_ap_vld,tree_scores_43_V_ap_vld,tree_scores_44_V_ap_vld,tree_scores_45_V_ap_vld,tree_scores_46_V_ap_vld,tree_scores_47_V_ap_vld,tree_scores_48_V_ap_vld,tree_scores_49_V_ap_vld,tree_scores_50_V_ap_vld,tree_scores_51_V_ap_vld,tree_scores_52_V_ap_vld,tree_scores_53_V_ap_vld,tree_scores_54_V_ap_vld,tree_scores_55_V_ap_vld,tree_scores_56_V_ap_vld,tree_scores_57_V_ap_vld,tree_scores_58_V_ap_vld,tree_scores_59_V_ap_vld,tree_scores_60_V_ap_vld,tree_scores_61_V_ap_vld,tree_scores_62_V_ap_vld,tree_scores_63_V_ap_vld,tree_scores_64_V_ap_vld,tree_scores_65_V_ap_vld,tree_scores_66_V_ap_vld,tree_scores_67_V_ap_vld,tree_scores_68_V_ap_vld,tree_scores_69_V_ap_vld,tree_scores_70_V_ap_vld,tree_scores_71_V_ap_vld,tree_scores_72_V_ap_vld,tree_scores_73_V_ap_vld,tree_scores_74_V_ap_vld,tree_scores_75_V_ap_vld,tree_scores_76_V_ap_vld,tree_scores_77_V_ap_vld,tree_scores_78_V_ap_vld,tree_scores_79_V_ap_vld,tree_scores_80_V_ap_vld,tree_scores_81_V_ap_vld,tree_scores_82_V_ap_vld,tree_scores_83_V_ap_vld,tree_scores_84_V_ap_vld,tree_scores_85_V_ap_vld,tree_scores_86_V_ap_vld,tree_scores_87_V_ap_vld,tree_scores_88_V_ap_vld,tree_scores_89_V_ap_vld,tree_scores_90_V_ap_vld,tree_scores_91_V_ap_vld,tree_scores_92_V_ap_vld,tree_scores_93_V_ap_vld,tree_scores_94_V_ap_vld,tree_scores_95_V_ap_vld,tree_scores_96_V_ap_vld,tree_scores_97_V_ap_vld,tree_scores_98_V_ap_vld,tree_scores_99_V_ap_vld,ap_clk,ap_rst,ap_start,ap_done,ap_idle,ap_ready,x_0_V[10:0],x_1_V[10:0],x_2_V[10:0],x_3_V[10:0],x_4_V[10:0],x_5_V[10:0],x_6_V[10:0],score_0_V[10:0],score_1_V[10:0],tree_scores_0_V[10:0],tree_scores_1_V[10:0],tree_scores_2_V[10:0],tree_scores_3_V[10:0],tree_scores_4_V[10:0],tree_scores_5_V[10:0],tree_scores_6_V[10:0],tree_scores_7_V[10:0],tree_scores_8_V[10:0],tree_scores_9_V[10:0],tree_scores_10_V[10:0],tree_scores_11_V[10:0],tree_scores_12_V[10:0],tree_scores_13_V[10:0],tree_scores_14_V[10:0],tree_scores_15_V[10:0],tree_scores_16_V[10:0],tree_scores_17_V[10:0],tree_scores_18_V[10:0],tree_scores_19_V[10:0],tree_scores_20_V[10:0],tree_scores_21_V[10:0],tree_scores_22_V[10:0],tree_scores_23_V[10:0],tree_scores_24_V[10:0],tree_scores_25_V[10:0],tree_scores_26_V[10:0],tree_scores_27_V[10:0],tree_scores_28_V[10:0],tree_scores_29_V[10:0],tree_scores_30_V[10:0],tree_scores_31_V[10:0],tree_scores_32_V[10:0],tree_scores_33_V[10:0],tree_scores_34_V[10:0],tree_scores_35_V[10:0],tree_scores_36_V[10:0],tree_scores_37_V[10:0],tree_scores_38_V[10:0],tree_scores_39_V[10:0],tree_scores_40_V[10:0],tree_scores_41_V[10:0],tree_scores_42_V[10:0],tree_scores_43_V[10:0],tree_scores_44_V[10:0],tree_scores_45_V[10:0],tree_scores_46_V[10:0],tree_scores_47_V[10:0],tree_scores_48_V[10:0],tree_scores_49_V[10:0],tree_scores_50_V[10:0],tree_scores_51_V[10:0],tree_scores_52_V[10:0],tree_scores_53_V[10:0],tree_scores_54_V[10:0],tree_scores_55_V[10:0],tree_scores_56_V[10:0],tree_scores_57_V[10:0],tree_scores_58_V[10:0],tree_scores_59_V[10:0],tree_scores_60_V[10:0],tree_scores_61_V[10:0],tree_scores_62_V[10:0],tree_scores_63_V[10:0],tree_scores_64_V[10:0],tree_scores_65_V[10:0],tree_scores_66_V[10:0],tree_scores_67_V[10:0],tree_scores_68_V[10:0],tree_scores_69_V[10:0],tree_scores_70_V[10:0],tree_scores_71_V[10:0],tree_scores_72_V[10:0],tree_scores_73_V[10:0],tree_scores_74_V[10:0],tree_scores_75_V[10:0],tree_scores_76_V[10:0],tree_scores_77_V[10:0],tree_scores_78_V[10:0],tree_scores_79_V[10:0],tree_scores_80_V[10:0],tree_scores_81_V[10:0],tree_scores_82_V[10:0],tree_scores_83_V[10:0],tree_scores_84_V[10:0],tree_scores_85_V[10:0],tree_scores_86_V[10:0],tree_scores_87_V[10:0],tree_scores_88_V[10:0],tree_scores_89_V[10:0],tree_scores_90_V[10:0],tree_scores_91_V[10:0],tree_scores_92_V[10:0],tree_scores_93_V[10:0],tree_scores_94_V[10:0],tree_scores_95_V[10:0],tree_scores_96_V[10:0],tree_scores_97_V[10:0],tree_scores_98_V[10:0],tree_scores_99_V[10:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "my_prj,Vivado 2019.1";
begin
end;
